# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 15:53
from __future__ import unicode_literals

from django.db import migrations

def create_initial_clusters(apps, schema_editor):
    Cluster = apps.get_model('cluster', 'Cluster')

    Cluster(title='Loja').save()
    Cluster(title='Produto').save()
class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_clusters),
    ]
